# Generated by Django 4.2.5 on 2023-09-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categorie',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Classic', 'Classic'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Comic', 'Comic'), ('Science', 'Science'), ('literature', 'Literature')], default='Classic', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='books/static/books/images/'),
        ),
    ]
