# Generated by Django 4.2.5 on 2023-09-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_categorie_book_is_best_seller_book_is_popular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(upload_to='static/images/'),
        )
    ]
