# Generated by Django 4.2.5 on 2023-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_book_image_alter_book_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_language',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
