# Generated by Django 4.2.5 on 2023-09-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users'),
        ),
    ]
